### ISSUE TITLE
Draft-js-plugins storybook not working

### ISSUE THREAD

**Issue by vcarrasc** [draft-js-plugins/draft-js-plugins#1553]
## Use-case/Problem

I'm trying to run the storybook of `draft-js-pulgins` and I' getting the following error. Is someone else experiencing this issue?

```
➜  draft-js-plugins git:(master) npm run storybook

> draft-js-plugins@0.0.0 storybook /Users/vcarrasco/Documents/workspace/draft-js-plugins
> start-storybook -p 6006 -s ./stories/public

info @storybook/react v6.0.28
info
info => Loading static files from: /Users/vcarrasco/Documents/workspace/draft-js-plugins/stories/public .
info => Loading presets
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Adding stories defined in ".storybook/main.js".
(node:58961) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17
		compilation.templatesPlugin("render-with-entry", (source, chunk, hash) => {
		            ^

TypeError: compilation.templatesPlugin is not a function
    at SetVarMainTemplatePlugin.apply (/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17:15)
    at Compilation.apply (/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/tapable/lib/Tapable.js:79:16)
    at Compilation.deprecated [as apply] (internal/util.js:89:15)
    at /Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/webpack/lib/LibraryTemplatePlugin.js:40:18
    at SyncHook.eval [as call] (eval at create (/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:630:30)
    at /Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:667:29
    at eval (eval at create (/Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/@storybook/core/node_modules/webpack/lib/DllReferencePlugin.js:72:15
    at /Users/vcarrasco/Documents/workspace/draft-js-plugins/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draft-js-plugins@0.0.0 storybook: `start-storybook -p 6006 -s ./stories/public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js-plugins@0.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by fxOne** [comment]
That's wired as it currently works for me. Did you installed the project via `yarn`? Because if you use `npm` you can may get newer dependencies as this project only has a `yarn.lock`.

**Comment by vcarrasc** [comment]
@fxOne thank you! I did not know I had to run it with `yarn`
