### ISSUE TITLE
Mention Plugin example throws DOMException

### ISSUE THREAD

**Issue by hasandogu** [draft-js-plugins/draft-js-plugins#1697]
## Environment

- @draft-js-plugins/editor version: 4.0.0
- plugin name and version: @draft-js-plugins/mention 4.0.0

## Description

We tried upgrading our plugins to 4.0.0 and found that the mention plugin is throwing various exceptions when we try to delete the trigger character (or all the characters).

We figured out the same also happens on the examples for the mention plugin. (https://www.draft-js-plugins.com/plugin/mention)

Below are a few of the different exceptions we can get on the samples page.
![image](https://user-images.githubusercontent.com/10977151/104375885-f1b87980-54d8-11eb-8566-885b22d5bc00.png)

```
react_devtools_backend.js:2430 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at vo (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:6080:19)
    at ku (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:6987:21)
    at t.unstable_runWithPriority (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:717:20)
    at $l (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:3471:29)
    at wu (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:6850:16)
    at ou (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:6585:13)
    at https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:3496:23
    at t.unstable_runWithPriority (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:717:20)
    at $l (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:3471:29)
    at Xl (https://www.draft-js-plugins.com/_next/static/chunks/framework.146c8bd33061333d4954.js:3492:13)
overrideMethod @ react_devtools_backend.js:2430
ro @ framework.146c8bd33061333d4954.js:5769
i.componentDidCatch.n.callback @ framework.146c8bd33061333d4954.js:6263
hi @ framework.146c8bd33061333d4954.js:3719
uo @ framework.146c8bd33061333d4954.js:5859
ku @ framework.146c8bd33061333d4954.js:7052
t.unstable_runWithPriority @ framework.146c8bd33061333d4954.js:717
$l @ framework.146c8bd33061333d4954.js:3471
wu @ framework.146c8bd33061333d4954.js:6850
ou @ framework.146c8bd33061333d4954.js:6585
(anonymous) @ framework.146c8bd33061333d4954.js:3496
t.unstable_runWithPriority @ framework.146c8bd33061333d4954.js:717
$l @ framework.146c8bd33061333d4954.js:3471
Xl @ framework.146c8bd33061333d4954.js:3492
Yl @ framework.146c8bd33061333d4954.js:3484
F @ framework.146c8bd33061333d4954.js:7906
Xt @ framework.146c8bd33061333d4954.js:2004
```

## Reproducible Demo

1. Try the first example on the examples page (https://www.draft-js-plugins.com/plugin/mention)
2. Type in '@' to mention someone. 
3. Select the mention
4. Delete the mention
5. Type in '@' followed by a few characters
6. Delete the mention characters including the '@'

**Comment by michaelwhelehan** [comment]
I too encountered this when I started using this last Sunday... my workaround for now was the wrap <Editor /> with in an ErrorBoundary component and just call this.forceUpdate in the componentDidCatch method.. this of course leads to other undesirable side effects like the cursor being out of whack but it's better than the whole page exploding for now

**Comment by fxOne** [comment]
I could only reproduce the error when the trigger was the first character in the editor. 

I released the new versions `@draft-js-plugins/mention@4.0.1` and `@draft-js-plugins/emoji@4.0.2` as the same issue occurred also there.

Can you please update and confirm if all issues are solved?

**Comment by hasandogu** [comment]
Thank you @fxOne for the fastest turnaround.

I imagine the ones on the website are also updated. I have now tried the Simple Example on the website and got the following. It seems to be happening after I write and delete '@' character twice without selecting anything.

![image](https://user-images.githubusercontent.com/10977151/104587701-2719b000-561c-11eb-99b5-6cb141110cca.png)

framework.146c8bd33061333d4954.js:1636 Uncaught TypeError: Cannot read property 'getIn' of undefined
    at P/Gd.t.exports (b0a93ee01c5d22f5806b506653752c49bbf12f67.3d78add3a2dc10b0eb43.js:9661)
    at b0a93ee01c5d22f5806b506653752c49bbf12f67.3d78add3a2dc10b0eb43.js:496
    at Object.o (framework.146c8bd33061333d4954.js:804)
    at p (framework.146c8bd33061333d4954.js:819)
    at framework.146c8bd33061333d4954.js:828
    at g (framework.146c8bd33061333d4954.js:833)
    at ot (framework.146c8bd33061333d4954.js:1627)
    at it (framework.146c8bd33061333d4954.js:1617)
    at ut (framework.146c8bd33061333d4954.js:1635)
    at mt (framework.146c8bd33061333d4954.js:1711)

Thank you so much for looking into this.

Once the plugin goes into this state, it doesn't seem to be able to recover from it as all the other samples become unusable or the plugin suggestions go to (0, 0) and show up there.

**Comment by erdillon** [comment]
I've noticed this too.

**Comment by fxOne** [comment]
The getIn issue is a draft-js/SSR issue which is already reported here: https://github.com/facebook/draft-js/issues/2121

**Comment by fxOne** [comment]
I can no longer reproduce this error on the current web site. @erdillon @hasandogu can you confirm that?

**Comment by hasandogu** [comment]
Thank you for looking into this @fxOne . I cannot reproduce the issue anymore. Closing this now.
