### ISSUE TITLE
Emoji and Mention plugins include lodash-es (ESM) which breaks CJS bundles

### ISSUE THREAD

**Issue by mimecuvalo** [draft-js-plugins/draft-js-plugins#1976]
- @draft-js-plugins/editor version: 4.1.0
- plugin name and version: emoji@4.4.0 and mention@4.3.1

## Description

I build and include draft-js as a CJS module (instead of ESM). However, this is causing this problems when including it with my build:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/mime/Sites/helloworld/node_modules/lodash-es/keys.js
require() of ES modules is not supported.
require() of /Users/mime/Sites/helloworld/node_modules/lodash-es/keys.js from /Users/mime/Sites/helloworld/node_modules/@draft-js-plugins/emoji/lib/index.cjs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename keys.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/mime/Sites/helloworld/node_modules/lodash-es/package.json.

    at new NodeError (node:internal/errors:329:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1109:13)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/mime/Sites/helloworld/node_modules/@draft-js-plugins/emoji/lib/index.cjs.js:7:12)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

I admit when it comes to these kind of build issues between CJS/ESM I could be totally doing something wrong on my end. It does strike me though it's only these two plugins that include `lodash-es` which is specifically only for ESM. I'm not sure how what would need to be done to make load the appropriate lodash depending if it's CJS or ESM.

Love the work - lemme know if I can assist further!

**Comment by fxOne** [comment]
Looks like this issue was introduced with PR #1819. I need to think about a better solution.
`@draft-js-plugins/emoji@4.2.0` and `@draft-js-plugins/mention@4.2.0` should work for you.

**Comment by tiborgg** [comment]
This is happening when running tests with Jest and Create React App as well:

```
 \node_modules\lodash-es\keys.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import arrayLikeKeys from './_arrayLikeKeys.js';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@draft-js-plugins/emoji/lib/index.cjs.js:7:12)
```

Downgrading `@draft-js-plugins/emoji` and `@draft-js-plugins/mention` to `4.2.0` fixes the issue.
