### ISSUE TITLE
Maximum depth exceeded when setting state in onChange

### ISSUE THREAD

**Issue by NatePillow** [draft-js-plugins/draft-js-plugins#2295]
## Environment

@draft-js-plugins/editor version: 4.1.0

Removed plugins to isolate issue.

## Description

Receiving a maximum depth exceeded error when updating state in onChange. Notably, the vanilla Editor found in the official draft-js library works without issue, but of course then I can't use plugins.

    Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
        at checkForNestedUpdates (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:174273:15)
        at scheduleUpdateOnFiber (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:172305:3)
        at Object.enqueueSetState (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:162942:5)
        at RichTextEditor.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:194645:16)
        at Object.RichTextEditor._this.onChange (http://localhost:3000/static/js/main.bundle.js:5190:19)
        at PluginEditor._this.onChange (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:1008:21)
        at PluginEditor.componentDidUpdate (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:1189:10)
        at commitLifeCycles (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:171154:24)
        at commitLayoutEffects (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:173896:7)
        at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors-node_modules_draft-js-plugins_editor_lib_index_esm_js-node_modules_draft-js-plugins_e-155b40.bundle.js:154420:14)

Not doing anything particularly odd with the handling. Preventing the state update in onChange makes the component load as expected. 

    constructor(props: ~snip~) {
        super(props);
        this.state = {
            editorState: this.props.editorState
        };
    }

    onChange = (editorState: EditorState) => {
        // Commenting out this setState line avoids the error
       this.setState({ editorState });
    };

    <Editor
        ref={innerRef}
        editorState={this.state.editorState}
        onChange={this.onChange}
        handleKeyCommand={this.handleKeyCommand}
        placeholder={placeholder || ''}
        plugins={[]}
        keyBindingFn={this.keyBindingFn}
    />

**Comment by fxOne** [comment]
Can you create a reproducible demo in codesandbox?

I have the feeling that there must be an issue in the setup as we have class based samples with plugins which are working. Maybe you have a look over there: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/docs/components/Examples/emoji/SimpleEmojiEditor/index.js

**Comment by NatePillow** [comment]
For future readers: This behavior can be due to the use of compositeDecorator, which the draft-js-plugins editor does not support, unlike the editor from the "official" draft-js library. Swapping over to the strategy outlined in the FAQ works:

https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-can-i-use-custom-decorators-with-the-plugin-editor

A more direct bug report on this issue:

https://github.com/draft-js-plugins/draft-js-plugins/issues/2143
