### ISSUE TITLE
Add Image issue

### ISSUE THREAD

**Issue by gmchaturvedi1** [draft-js-plugins/draft-js-plugins#741]
i am just following addImage example of draft-js-image plugin the followoing error is coming onclick 

imageAdd.js:47 Uncaught TypeError: _this.props.modifier is not a function
    at ImageAdd._this.addImage (http://localhost:3006/static/js/bundle.js:202205:29)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3006/static/js/bundle.js:17146:17)
    at executeDispatch (http://localhost:3006/static/js/bundle.js:16929:22)
    at Object.executeDispatchesInOrder (http://localhost:3006/static/js/bundle.js:16949:8)
    at executeDispatchesAndRelease (http://localhost:3006/static/js/bundle.js:16340:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3006/static/js/bundle.js:16351:11)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:3006/static/js/bundle.js:17249:10)
    at Object.processEventQueue (http://localhost:3006/static/js/bundle.js:16554:8)
    at runEventQueueInBatch (http://localhost:3006/static/js/bundle.js:24176:19)

can anyone help me out on this.

Reagrds
gmchaturvedi

**Comment by gmchaturvedi1** [comment]
my problem is solved by installing @2.0.0..beta11n install .Thanks
