### ISSUE TITLE
image plugin crital bug causing the editor to stop working

### ISSUE THREAD

**Issue by eldyvoon** [draft-js-plugins/draft-js-plugins#778]
On this image demo page
https://www.draft-js-plugins.com/plugin/image

inside any editor that has image, click on the right side of the image, then press enter. After that the behavior of the editor will be broken. You can see the error in chrome inspect shows:
```

invariant.js:40 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at a (https://www.draft-js-plugins.com/app.js:1:1650)
    at Object.__get (https://www.draft-js-plugins.com/app.js:6:450526)
    at t.getEntity (https://www.draft-js-plugins.com/app.js:20:12715)
    at Object.blockRendererFn (https://www.draft-js-plugins.com/app.js:6:437195)
    at https://www.draft-js-plugins.com/app.js:34:934607
    at Array.forEach (native)
    at https://www.draft-js-plugins.com/app.js:34:934548
    at t.render (https://www.draft-js-plugins.com/app.js:34:1112823)
    at f._renderValidatedComponentWithoutOwnerOrContext (https://www.draft-js-plugins.com/app.js:34:1017178)
    at f._renderValidatedComponent (https://www.draft-js-plugins.com/app.js:34:1017305)
```

**Comment by ghotiphud** [comment]
Seeing the same.  block.getEntityAt(0) in the image plugin blockRendererFn is returning null.  

`invariant.js:44 Uncaught Error: Unknown DraftEntity key.
    at invariant (http://localhost:3000/app.js:1978:15)
    at Object.__get (http://localhost:3000/app.js:26463:59)
    at ContentState.getEntity (http://localhost:3000/app.js:34298:24)
    at Object.blockRendererFn (http://localhost:3000/app.js:24605:35)
    at http://localhost:3000/app.js:74961:43
    at Array.forEach (native)
    at http://localhost:3000/app.js:74959:17
    at DraftEditorContents.render (http://localhost:3000/app.js:102069:28)
    at http://localhost:3000/app.js:88987:21
    at measureLifeCyclePerf (http://localhost:3000/app.js:88266:12)`

**Comment by juliankrispel** [comment]
Thanks for reporting this! If anyone wants to take up this bug, please do!
